### ISSUE TITLE
Personalization Semantics Explainer and  Module 1 - Adaptable Content

### ISSUE THREAD

**Issue by pes10k** [w3cping/privacy-reviews#1]
- Explainer - https://www.w3.org/TR/personalization-semantics-1.0/
- Module 1 - https://www.w3.org/TR/personalization-semantics-content-1.0/
- Privacy and security self-review - https://github.com/w3c/personalization-semantics/issues/131
- Wiki - https://github.com/w3c/personalization-semantics/wiki/
- Getting started page - https://github.com/w3c/personalization-semantics/wiki/Getting-started-with-personalization-semantics
- Github repo - https://github.com/w3c/personalization-semantics/issues

**Comment by jumde** [comment]
- [ ] Exposure of personalization preferences to third parties exposes fingerprinting surface: https://github.com/w3c/personalization-semantics/issues/131#issuecomment-599796904

**Comment by jumde** [comment]
There is no fingerprinting surface here, great explanation by john here: https://github.com/w3c/personalization-semantics/issues/131#issuecomment-614312781
