### ISSUE TITLE
CSS Cascading and Inheritance Level 3

### ISSUE THREAD

**Issue by pes10k** [w3cping/privacy-reviews#14]
Privacy review requested by the CSSWG on Sept 14, 2020

Link to spec: https://www.w3.org/TR/css-cascade-3/

Request to file issues at: https://github.com/w3c/csswg-drafts/labels/css-cascade-3

Review to be discussed on PING call on TBD

Go to https://github.com/w3cping/tracking-issues/issues to track the progress of any issues raised as a result of the privacy review.

**Comment by sandandsnow** [comment]
Update: privacy review to be discussed in PING meeting on 24 September 2020

**Comment by sandandsnow** [comment]
Privacy review discussed in PING meeting on 24 September 2020.
