### ISSUE TITLE
WebRTC Priority Control API

### ISSUE THREAD

**Issue by pes10k** [w3cping/privacy-reviews#17]
Spec: https://www.w3.org/TR/2020/WD-webrtc-priority-20200922/
Explainer: https://github.com/w3c/webrtc-priority/blob/master/explainer.md
Privacy considerations: https://github.com/w3c/webrtc-priority/blob/master/security-privacy-questionnaire.md
Repo: https://github.com/w3c/webrtc-priority

**Comment by sandandsnow** [comment]
[Privacy review](https://lists.w3.org/Archives/Public/public-privacy/2020JulSep/0038.html) requested by the WebRTC WG on 24 September 2020

**Comment by sandandsnow** [comment]
Review to be discussed on PING call on 15 October 2020.

Go to https://github.com/w3cping/tracking-issues/issues to track the progress of any issues raised as a result of the privacy review.
