### ISSUE TITLE
CSS Text Module Level 3

### ISSUE THREAD

**Issue by sandandsnow** [w3cping/privacy-reviews#19]
[Privacy review](https://lists.w3.org/Archives/Public/public-privacy/2020OctDec/0004.html) requested by the CSS WG on 6 October 2020.

Spec: https://www.w3.org/TR/css-text-3/

Privacy and security considerations: https://www.w3.org/TR/css-text-3/#priv-sec

Answers to Self-review: security and privacy questionnaire: https://lists.w3.org/Archives/Public/public-privacy/2020OctDec/0004.html

The WG has requested that we raise any issues in the csswg GitHub repo: https://github.com/w3c/csswg-drafts/issues

Review to be discussed on PING call on 15 October 2020.

Go to https://github.com/w3cping/tracking-issues/issues to track the progress of any issues raised as a result of the privacy review.

**Comment by kdzwinel** [comment]
For the record, I posted our questions about the dictionaries here - https://github.com/w3c/csswg-drafts/issues/5630 .
