### ISSUE TITLE
TTML Profiles for Internet Media Subtitles and Captions 1.2

### ISSUE THREAD

**Issue by pes10k** [w3cping/privacy-reviews#2]
Spec - https://w3c.github.io/imsc/imsc1/spec/ttml-ww-profiles.html
Repo - https://github.com/w3c/imsc/

**Comment by npdoty** [comment]
Review here: https://lists.w3.org/Archives/Public/public-privacy/2020JanMar/0055.html

**Comment by npdoty** [comment]
Separate call with TTWG, relevant minutes here: https://www.w3.org/2020/04/02-tt-minutes.html#t08

Some issue or issues may be moved to TTML; there's a PR for non-normative text; there was also a tentative discussion of a normative mitigation for font-enumeration.

**Comment by sandandsnow** [comment]
Closing issue as the review has been undertaken.

(Note: there may still be outstanding privacy considerations identified in the review that have not yet been resolved. See https://github.com/w3cping/tracking-issues/issues)
