### ISSUE TITLE
Web Authentication Level 2

### ISSUE THREAD

**Issue by sandandsnow** [w3cping/privacy-reviews#20]
[Privacy review](https://lists.w3.org/Archives/Public/public-privacy/2020OctDec/0018.html) requested by the Web Authentication WG on 19 October 2020.

Spec: https://w3c.github.io/webauthn/

This is an incremental update to WebAuthn Level 1 - https://www.w3.org/TR/2019/REC-webauthn-1-20190304/

Reported substantive changes since Rec:
* Added new method to allow Discoverable/Resident Credentials Preferred
* New methods added for Attestation Objects
* Added Enterprise Attestation, Apple Attestation
* Added Large Blob storage and credential properties
* Modified cross-origin iFrame usage (only 'get' command)
* Removed unused extensions (they remain in Level 1); also simple tx auth, generic tx auth, UVI, biometrics.
* Clarified some inputs and outputs in extensions
* Fixed some serialization issues with JSON parser

Privacy Considerations: https://www.w3.org/TR/webauthn-2/#sctn-privacy-considerations
WG welcomes comments on github - https://github.com/w3c/webauthn/issues

Review to be discussed on PING call on 5 November 2020.

Go to https://github.com/w3cping/tracking-issues/issues to track the progress of any issues raised as a result of the privacy review.

**Comment by sandandsnow** [comment]
Update: Given the length of the specification, the full discussion of the review will be postponed to the PING call on 19 November 2020.

**Comment by jumde** [comment]
- [ ] Permission prompt before requesting location information - https://github.com/w3cping/tracking-issues/issues/147

**Comment by sandandsnow** [comment]
This privacy review was discussed on the PING call on 19 November 2020.
