### ISSUE TITLE
Accessible Rich Internet Applications  (WAI-ARIA) 1.2

### ISSUE THREAD

**Issue by sandandsnow** [w3cping/privacy-reviews#21]
[Privacy review](https://lists.w3.org/Archives/Public/public-privacy/2020OctDec/0024.html) requested by the ARIA WG on 27 October 2020.

Specification: https://raw.githack.com/w3c/aria/2020-09_CR/index.html

The specification provides a framework to improve the accessibility and interoperability of web content and applications.

Changes since ARIA 1.1 : https://raw.githack.com/w3c/aria/2020-09_CR/index.html#substantive-changes-since-the-last-public-working-draft 

The WG reports that changes mostly consist of the addition of roles to get closer to parity with HTML to allow the creation of accessible Web components.

This specification is in the “almost CR” stage of development, so the WG expects it to transition, in more or less its current form, after completing horizontal review.

The WG reports that they "do not have a privacy and security section as there was no content to add".

Answers to the Self-review: Security and Privacy Questionnaire: https://lists.w3.org/Archives/Public/public-privacy/2020OctDec/0024.html

They have asked that we raise any issues in the ARIA GitHub repo: https://github.com/w3c/aria/issues

Review to be assigned on PING call on 5 November 2020, and discussed on PING call 19 November 2020.

Go to https://github.com/w3cping/tracking-issues/issues to track the progress of any issues raised as a result of the privacy review.

**Comment by pes10k** [comment]
https://github.com/w3c/aria/issues/1371
