### ISSUE TITLE
CSS Sizing Level 3

### ISSUE THREAD

**Issue by sandandsnow** [w3cping/privacy-reviews#22]
[Privacy review](https://lists.w3.org/Archives/Public/public-privacy/2020OctDec/0021.html) requested by the CSS WG on 23 October 2020

Specification: https://www.w3.org/TR/css-sizing-3/

The CSS module defines the various sizing properties and concepts used throughout CSS. 

New features since CSS2 are summarized in https://www.w3.org/TR/css-sizing-3/#changes-3

The WG advised that the specification is in the “almost CR” stage of development, so they expect it to transition, in more or less its current form, after completing horizontal review.

Privacy and Security Considerations section: https://www.w3.org/TR/css-sizing-3/#priv-sec

Answers to Self-review: Security and Privacy Questionnaire: https://lists.w3.org/Archives/Public/public-privacy/2020OctDec/0021.html

The WG has asked that we  raise any issues in the csswg GitHub repo: https://github.com/w3c/csswg-drafts/issues

Review to be assigned on PING call on 5 November 2020, and discussed on PING call 19 November 2020.

Go to https://github.com/w3cping/tracking-issues/issues to track the progress of any issues raised as a result of the privacy review.

**Comment by NalaGinrut** [comment]
I don't see any apparent issue of privacy in this spec.  @pes10k

**Comment by sandandsnow** [comment]
This privacy review was discussed at the PING call on 19 November 2020.
