### ISSUE TITLE
CSS Box Model Module Level 3

### ISSUE THREAD

**Issue by sandandsnow** [w3cping/privacy-reviews#23]
[Privacy review](https://lists.w3.org/Archives/Public/public-privacy/2020OctDec/0025.html) requested by the CSS WG on 28 October 2020.

Specification: https://www.w3.org/TR/css-box-3/

The specification describes the margin and padding properties, which create spacing in and around a CSS box, and defines a bunch of terminology used throughout the CSS layout specs. 

Changes since CSS2 are summarized in: https://www.w3.org/TR/css-box-3/#changes
and basically consist of
 * updating the prose to account for vertical writing modes
 * defining a shared list of box-edge keywords for use in other properties

There are no new features.

The WG advises that it is really just a redrafting of a very basic piece of CSS2.

They have asked that we raise any issues in the csswg GitHub repo: https://github.com/w3c/csswg-drafts/issues

Review to be assigned on PING call on 5 November 2020, and discussed on PING call 19 November 2020.

Go to https://github.com/w3cping/tracking-issues/issues to track the progress of any issues raised as a result of the privacy review.

**Comment by NalaGinrut** [comment]
I don't see any apparent issue of privacy in this spec. I think it's fine so far. @pes10k

**Comment by pes10k** [comment]
Thanks! @NalaGinrut could you join the next PING call (this coming Thursday at 9am PDT) and talk us through the spec and your findings?  If so, then i think we'd be in a good place to consider this review (and https://github.com/w3cping/privacy-reviews/issues/22) resolved!

**Comment by NalaGinrut** [comment]
@pes10k I would like to join! Let's double-check the time, Thursday 9 am PDT is GMT+8, Nov 19, 5 pm, right?

**Comment by NalaGinrut** [comment]
Hmm...I think it should be Nov 20, 1 am in Beijing time.

**Comment by pes10k** [comment]
Oh! Okay, if you're certain the time works for you, than that would be very appreciated! And if the time is prohibitive, please let me know too, and we can do our best to figure something out.  But otherwise, will be very glad and grateful if you can join us on the PING call.  Thanks again!

**Comment by NalaGinrut** [comment]
@pes10k 
For a better minute about these 2 specs review, I list my points here, in case anything missing in the meeting:

1. The information of width, height, padding, margin, and the sizing of the UI box are usually public to any visitors, so they may not be treated as privacy.
2. The information provided in the specs can be changed on the fly by responsive web rendering, which is a modern popular way of web frontend. So this information is not unique that is not very useful for generating fingerprints.
3. One more thing that I didn't mention in the meeting, these specs are only related to the attributions definition of the UI box, not about the API which can collect these information that can be transmitted out of the user's scope. So I don't think there's concern for privacy leaking.

**Comment by pes10k** [comment]
Thanks again @NalaGinrut !
