### ISSUE TITLE
DOM standard

### ISSUE THREAD

**Issue by sandandsnow** [w3cping/privacy-reviews#24]
Horizontal review of the commits of the DOM Standard between 19 June 2019 (b5eac4d) and 15 June 2020 (ad06a4c) [requested](https://lists.w3.org/Archives/Public/public-privacy/2020OctDec/0031.html) by the HTML WG on 17 November 2020. 

Link to commits: https://github.com/whatwg/dom/commits/master?before=ad06a4c686a62a2a0f175125932200930364c170+35

Background: The WHATWG published a [new Review Draft](https://dom.spec.whatwg.org/review-drafts/2020-06/) of the DOM Standard on 15 June 2020. The HTML WG plans to take this Review Draft to W3C Recommendation in 2021.

The WG has requested that Issues identified during wide and horizontal review be filed directly on the [WHATWG HTML repository](https://github.com/whatwg/html/issues/). They have also asked that we send a pointer to the place where we track issues by email to public-html@w3.org.

They also advise that they expect issues to be opened, discussed, and resolved in WHATWG space, but the HTML WG can provide an escalation point if one is needed. The WHATWG FAQ explains how to raise issues here: https://whatwg.org/faq#adding-new-features.

The WG plans to open the CFC to adopt the HTML Standard Review Draft as W3C CR in January, so they request that the review be completed by 29 December 2020.

**Comment by pes10k** [comment]
Review completed by @pes10k and reported at the 17 December 2020 call
