### ISSUE TITLE
Audio Output Devices API (call for wide review)

### ISSUE THREAD

**Issue by sandandsnow** [w3cping/privacy-reviews#29]
The WebRTC WG issued a [call for wide review](https://lists.w3.org/Archives/Public/public-review-announce/2020Nov/0012.html) on 27 November 2020.

Spec: https://www.w3.org/TR/2020/CRD-audio-output-20201127/

The WebRTC and Device and Sensors Working Group intend to publish this specification as a Candidate Recommendation soon. 

The WGs ask that issues be raised in GitHub or sent to their mailing list - public-webrtc@w3.org

**Comment by pes10k** [comment]
Issues filed here: https://github.com/w3c/mediacapture-output/issues/116
