### ISSUE TITLE
Trace Context Level 1

### ISSUE THREAD

**Issue by npdoty** [w3cping/privacy-reviews#4]
Review here: https://lists.w3.org/Archives/Public/public-trace-context/2020Feb/0004.html
... which specifically noted we should track reviews status as issues in this repo so that we're sure to come back to them and not too late.

**Comment by npdoty** [comment]
Group has started opening github issues, and reply to the issues raised in email starts here: https://github.com/w3c/trace-context/issues/392

**Comment by sandandsnow** [comment]
Closing issue as the review has been undertaken.

(Note: there may still be outstanding privacy considerations identified in the review that have not yet been resolved. See https://github.com/w3cping/tracking-issues/issues)
