### ISSUE TITLE
Privacy and accessibility [policy. W3C wiki]

### ISSUE THREAD

**Issue by harounmh** [w3cping/privacy-reviews#5]
Page here: https://www.w3.org/WAI/APA/wiki/Privacy_and_accessibility

**Comment by harounmh** [comment]
**Privacy review - 16 Apr 2020**

_Format note: each sub-section is accompanied with a directive on severity and potential points of discussion._

-----

`Privacy related issues for people with disabilities`
Questions surfaced and answered below with **bold titles**.

-----

`User needs for privacy`
Condensing and decrypting legalese for clear and relatable language on privacy. Data tied to vulnerable people who lean on online accessibility has a much higher standard of privacy protection. Clear mechanisms for explicit consent from them and their carers is of vital importance. Broad points for consideration (partly guided by the [Bureau of Internet Accessibility](https://www.boia.org/blog/accessibility-is-privacy-and-security)):

- Labelling graphics appropriately.
- Ensuring that all functionality is available via the keyboard.
- Providing users with enough time to read and use content.
- Making sure that websites and apps are easily navigable by screen readers used by individuals who are blind.
- Using icons and other visual elements that benefit people with cognitive disabilities.

[JD Supra guidance](https://www.jdsupra.com/legalnews/ccpa-privacy-faqs-how-can-companies-42524/) is particularly useful and worth exploring as the beginnings of a privacy-accessibility framework. In summary:
- Online privacy notices would ideally use industry-standard technologies such as HTML, JavaScript and Java or other code generally accessible to audio-readers.
- Online privacy notices that utilise PDF attachments, or are displayed within a PDF, could include character recognition. 
- Online privacy notices could specify document language in HTML to enable people who use screen readers to calibrate their speech synthesizer.
- Online privacy notices could utilise document structure tags such as headings, paragraphs, sections, tables and other page elements.
- Businesses could utilise alternative text for non-text elements (e.g., do not sell buttons).

_Discussion note: What is the best framework we can provide to accessibility teams to execute this?_

-----

`Requirements for privacy`
The CCPA does, rather positively, [set out accessibility measures](https://www.lexology.com/library/detail.aspx?g=0da1ab2b-849b-48c9-b09d-11f73c14566c) with fines for violation, however [Thurston v Midvale](https://law.justia.com/cases/california/court-of-appeal/2019/b291631.html) [2019] highlights accessibility failures on print-related disability and the pitfalls of not setting privacy-centric guidelines: 

> Using the telephone number as an alternative would not have provided her with the same privacy and independence that a fully accessible website offered or that the non-accessible website offered a sighted person.

I'd be interested in bringing [Deque](https://www.deque.com/) into the conversation on addressing an accessibility blueprint for this re: [CCPA, §99.308(2)(d)](https://ccpa-info.com/wp-content/uploads/2019/10/ccpa-proposed-regs.pdf).

_Discussion note: How can an approach be templatised at browser level to include applications outside of CCPA jurisdiction?_

-----

**Fingerprinting - severity: low/mid**
A concerning consequence of fingerprinting = profiling of vulnerable users via system fonts, screen resolution, plugins, graphics card, etc. increasing their risk vectors.

_Discussion note: I defer to those with the technical browser knowledge to address safe default `privacy.resistFingerprinting` browsing environments for vulnerable users._

-----

**Social media privacy and monitoring - severity: mid**
The original contributor cited [this research](https://ecu.on.worldcat.org/oclc/7261499889) on how social media participation can increase social capital of those with intellectual disabilities.

_Discussion note: It's absolutely something to be supported, but how can we as a group ensure these vulnerable individuals have privacy defaults that shield them from tracking and profiling that is generally non-discriminatory of disability while also maintaining usability? Protection from [Federal snooping](https://www.reuters.com/article/us-column-miller-socialmedia/u-s-government-weighs-social-media-snooping-to-detect-social-security-fraud-idUSKCN1RA12R) re: SSDI fraud detection is also a concern._

-----

**XR environments - severity: mid/high**
For clarity (from [W3C](https://www.w3.org/TR/xaur/) itself), XR environments include but are not limited to:
- Immersive or augmented environments.
- Head mounted displays, whether they are opaque, transparent, or utilise video passthrough.
- Mobile devices with positional tracking.
- Fixed displays with head tracking capabilities.

Particular focus should be on healthtech (and secondarily, educational) implementations, and companies that collect [Special category data](https://ico.org.uk/for-organisations/guide-to-data-protection/guide-to-the-general-data-protection-regulation-gdpr/lawful-basis-for-processing/special-category-data/) where mechanisms are required to handle it with special care.

The original contributor referred to [this research](https://ecu.on.worldcat.org/oclc/6881055775), which brought to light security and privacy concerns in relation to remote software access to medical implants (e.g. pacemakers). The bounds of [ethics and individual consent regarding telecare](https://www.livingmadeeasy.org.uk/scenario.php?csid=43) is a massive grey area where it would be useful for us to provide [structured guidance](https://www.atdementia.org.uk/editorial.asp?page_id=47).

_Discussion note: what privacy bounds (e.g. tokenising PII) can be set on the collection of this data? What role does legitimate interest play when it comes to companies collecting user information as a means to improve their product for higher performance where improved function is critical to health support for that individual? Consistent issues arise around consent and tracking that should be addressed, particularly around health data._

**Comment by sandandsnow** [comment]
Closing issue as the review has been undertaken.

(Note: there may still be outstanding privacy considerations identified in the review that have not yet been resolved. See https://github.com/w3cping/tracking-issues/issues)
