### ISSUE TITLE
Is there a way to export or import personal privacy model for the browser?

### ISSUE THREAD

**Issue by NalaGinrut** [w3cping/privacy-reviews#6]
Hi folks!

We've reviewed many cases, and left a lot of suggestions to opt-in. However, the users' experiences will be downgraded by so many opt-in. I wonder if there's a way, like a format (json or xml, etc) to import or export the personal privacy model to let users store their choices of all these opt-in permanently. 

If no, maybe we we should create a standard for it.

**Comment by npdoty** [comment]
This repo is for tracking specific privacy reviews of specifications.

If you have suggestions or ideas for privacy configuration or privacy preferences, I think the WICG Discourse might be a better place to brainstorm: https://discourse.wicg.io/

There was past experience at W3C with defining a Platform for Privacy Preferences (P3P) which might be some relevant prior art. If you have more very specific use cases, that might be the most helpful in identifying what would be useful to standardize.
