### ISSUE TITLE
WebXR Device API 

### ISSUE THREAD

**Issue by sandandsnow** [w3cping/privacy-reviews#9]
[Privacy review requested](https://lists.w3.org/Archives/Public/public-privacy/2020JulSep/0016.html) by the Immersive Web WG on 7 August 2020.

Current ED: https://immersive-web.github.io/webxr/

Security and Privacy considerations: https://immersive-web.github.io/webxr/#security

Explainer: https://github.com/immersive-web/webxr/blob/master/privacy-security-explainer.md

Review discussed on PING call on [20 August 2020](https://www.w3.org/Privacy/IG/summaries/PING-minutes-20200820).

Go to https://github.com/w3cping/tracking-issues/issues to track the progress of any issues raised as a result of the privacy review.

**Comment by pes10k** [comment]
Just to follow up, this issue is still present in the spec: https://github.com/w3cping/tracking-issues/issues/52

**Comment by sandandsnow** [comment]
Closing issue as the review has been undertaken. 

(Note: there may still be outstanding privacy considerations identified in the review that have not yet been resolved. As at closing this issue, w3cping/tracking-issues#52 is still open)

**Comment by pes10k** [comment]
This was re-reviewed by myself.  The spec had changes made in the interim between my review and the recent requested advancement. @dmarti and I re-reviewed those changes and found no signifigant changes w/r/t privacy, and so no concerns PING side with the spec advancing
